### ISSUE TITLE
Could you please provide a Java version Demo?

### ISSUE THREAD

**Issue by spysoos** [pthomain/dejavu#37]
Could you please provide a Java version Demo? That maybe let this library more popular，Thank you

**Comment by pierre-bud** [comment]
Hi @spysoos, thanks for your comment. 
Unfortunately, I don't have time to provide a Java implementation, as I'm working full time and only maintaining this library in my spare time. However, if you want to quickly see how the library works, you can take a look at the demo app: https://play.google.com/store/apps/details?id=uk.co.glass_software.android.cache_interceptor.demo

If you want to set it up in Java, the easiest way is to build the default implementation like so:
```java
Serialiser serialiser = new SimpleSerialiser() {
    @NotNull
    @Override
    public <O> String serialise(@NotNull O o) {
        return gson.toJson(o);
    }

    @Override
    public <O> O deserialise(@NotNull String s, @NotNull Class<O> aClass) {
        return gson.fromJson(s, aClass);
    }
};

RetrofitCallAdapterFactory callFactory = DejaVu.Companion.builder()
        .build(context, serialiser)
        .retrofitCallAdapterFactory;

Retrofit retrofit = new Retrofit.Builder()
        .addCallAdapterFactory(callFactory)
        .build();

YourApiClient yourApiClient = retrofit.create(YourApiClient.class);
```

Then you can define your client like so:
```java
interface YourApiClient {
    @Cache
    YourResponse callApi();
}      
```

You can then annotate your client's methods with any of the annotations available in the `uk.co.glass_software.android.dejavu.retrofit.annotations` package. There is JavaDoc for each operation in the `uk.co.glass_software.android.dejavu.configuration.CacheInstruction` class.

I'll write a proper wiki for this at some point but in the meantime, I hope that helps. Let me know if you have any issues.

**Comment by spysoos** [comment]
thank you for your reply, i got it
